version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 045291957223.dkr.ecr.ap-south-1.amazonaws.com/node-app
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 045291957223.dkr.ecr.ap-south-1.amazonaws.com/node-app:${CODEBUILD_BUILD_NUMBER} .
      - printf '[{"imageUri":"%s"}]' 045291957223.dkr.ecr.ap-south-1.amazonaws.com/node-app:${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json
      - docker tag 045291957223.dkr.ecr.ap-south-1.amazonaws.com/node-app:${CODEBUILD_BUILD_NUMBER} 045291957223.dkr.ecr.ap-south-1.amazonaws.com/node-app:dev
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 045291957223.dkr.ecr.ap-south-1.amazonaws.com/node-app:${CODEBUILD_BUILD_NUMBER}
      - docker push 045291957223.dkr.ecr.ap-south-1.amazonaws.com/node-app:dev
artifacts:
  files: 
    - 'imagedefinitions.json'      
      
      
